### ISSUE TITLE
Plugin layout overrides app layout : difficult to integrate properly the plugin in an existant application

### ISSUE THREAD

**Issue by lh-import** [cakephp/api_generator#5]
Created by **[Predominant](https://github.com/predominant)**, 12th Dec 2009. *(originally [Lighthouse ticket #2](http://cakephp.lighthouseapp.com/projects/42879/tickets/2))*:
- - - -

(Reported by: scharrier)

As there's a default.ctp file in the plugin layout's directory, it's not actually possible to integrate properly (= with same design) the api_generator as a module in an existant application, without modifying his layout.
I think it would be better to include the .js, .css and menus directly in the views (not inline), in order to delete default.ctp. Integration with existing dev environnement would be better ! For an example, we actually have a dev environment, with functionnals tests, user documentation wiki, unit tests reports, and API doc, in the same app (so with the same menu in every pages, same design, etc ...). We just want all our plugins to use the same design and navigation schema !
Thanks a lot for your answer :-) Sébastien Charrier

**Comment by FabianOudhaarlem** [comment]
Wrong solution. I fixed it by renaming the layout file to api_generator.ctp and inside the api_generator_app_controller i added `public $layout = 'api_generator';`

**Comment by markstory** [comment]
@FabianOudhaarlem This project is basically abandoned at this point. You might want to consider using ApiGen or PHPDocumentor instead. They are more well maintained and should have fewer issues long term.
